### ISSUE TITLE
[question] Can charpacker.py used to convert a png into a multicolor charset?

### ISSUE THREAD

**Issue by shazz** [dkrajzew/c64#8]
Hi,
I thought I could use charpacker to convert an image (respecting the multicolor constraints) into a set of custom character data and screen memory data ($0400+) and color RAM data ($d800+) but when trying it only found 1 character:

````
Charpacking succesfull, needed 1 chars.
saving screen...
saving charset...
````

Did I misunderstand the goal of this script?

**Comment by dkrajzew** [comment]
Well, partially. The tool does not consider colors. It basically looks for same characters (8x8 pixels) in the image and saves them as a charset with just unnique characters and a matrix of bytes that describes how to align the characters.

Dealing with different colors would be a nice feature, you may add it to the feature request list.

Converting a PC-bitmap into something that considers the c64 color limitations would require a different tool.

**Comment by shazz** [comment]
Ok makes sense. Thanks!

**Comment by dkrajzew** [comment]
Hello!

Ok!? Great! Is it available anywhere?

Sincerely,
Daniel


Am Mo., 30. Nov. 2020 um 23:24 Uhr schrieb shazz <notifications@github.com>:

**Comment by shazz** [comment]
Oh :) I can do that :) It currently converts an image into a charset, generates a tiles fullscreen and also converts an image into sprites data. Let me set up a repo for that.
